# Generated by Django 3.0.5 on 2020-05-09 21:02

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='member_img/%Y/%m/%d/')),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('sub_team', models.CharField(max_length=120)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedIn', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
